include macchiato.conf
# bold_italic_font auto

font_size 12.0

hide_window_decorations yes

background_opacity 0.5
background_blur 2


# BEGIN_KITTY_FONTS
font_family      CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

modify_font cell_height 2px
