# background image
background {
  monitor = eDP-1
  path = $HOME/.config/hypr/assets/wallpaper.png
  blur_passes = 3
  blur_size = 4
}

# password prompt
input-field {
  monitor = eDP-1

  dots_size = 0.25
  dots_center = true
  font_family = CaskaydiaCove Nerd Font
  font_color = rgba(36, 39, 58, 1.0)
  fade_on_empty = false

  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgba(130, 130, 130, 0.5)

  size = 250, 30
  position = 0, -420
}

# time
label {
  monitor = eDP-1
  text = $TIME
  text_align = center
  font_size = 110
  font_family = SF Pro Display Bold
  color = rgba(255, 255, 255, 0.4)
  position = 0, 350
}

#date
label {
  monitor = eDP-1
  text = cmd[update:86400] echo "$(date "+%A, %d %B")"
  text_align = center
  font_size = 15
  font_family = SF Pro Display Bold
  color = rgba(255, 255, 255, 0.4)
  position = 0, 430
}

#music info
## player area
shape {
  monitor = eDP-1
  size = 450, 150
  color = rgba(100, 100, 100, 0.3) # no fill
  rounding = 20
  position = 0, -250
}

## cover art
image {
  monitor = eDP-1
  path = /tmp/album_art.png
  rounding = 12
  size = 120
  position = -150, -250
  
  border_size = 0

  reload_time = 1
}

## track name
label {
  monitor = eDP-1
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh --title
  color = rgba(200, 200, 200, 0.6)
  font_family = SF Pro Display Bold
  font_size = 12
  position = 890, -210
  halign = left
}
## album name
label {
  monitor = eDP-1
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh --album
  color = rgba(200, 200, 200, 0.6)
  font_family = SF Pro Display Bold
  font_size = 12
  position = 890, -240
  halign = left
}
## artist name
label {
  monitor = eDP-1
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh --artist
  color = rgba(200, 200, 200, 0.6)
  font_family = SF Pro Display Bold
  font_size = 12
  position = 890, -270
  halign = left
}
## player name
label {
  monitor = eDP-1
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh --player
  color = rgba(200, 200, 200, 0.6)
  font_family = CaskaydiaCove Nerd Font
  font_size = 15
  position = 1154, -195
  halign = left
}

## controls
### previous
label {
  monitor = eDP-1
  text = 󰙤 ‎
  color = rgba(200, 200, 200, 0.6)
  font_family = CaskaydiaCove Nerd Font
  font_size = 17
  position = -50, -300
  onclick = playerctl previous
}
### play-pause
label {
  monitor = eDP-1
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh --status 
  color = rgba(200, 200, 200, 0.6)
  font_family = CaskaydiaCove Nerd Font
  font_size = 17
  position = -1, -300
  onclick = playerctl play-pause
}
### next
label {
  monitor = eDP-1
  text = 󰙢 ‎
  color = rgba(200, 200, 200, 0.6)
  font_family = CaskaydiaCove Nerd Font
  font_size = 17
  position = 50, -300
  onclick = playerctl next
}
#animations
animations {
  enabled = true
  
  bezier = easeOutQuint,   0.23, 1,    0.32, 1
  bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
  bezier = linear,         0,    0,    1,    1
  bezier = almostLinear,   0.5,  0.5,  0.75, 1
  bezier = quick,          0.15, 0,    0.1,  1

  animation = fade, 1, 4, linear
  animation = fadeIn, 1, 4, linear, slide left
  animation = fadeOut, 1, 4, linear, slide bottom
  animation = inputFieldDots, 1, 2, linear
}
