source = ~/.config/hypr/macchiato.conf

background {
  monitor =
  path = ~/.config/hypr/wallpaper.png
  blur_passes = 2
}

# INPUT
input-field {
  monitor =
  size = 15%, 3%

  inner_color = rgba(160, 160, 160, 0.6)
  outline_thickness = 0
  check_color = $green
  fail_color = $red

  dots_size = 0.3
  font_color = $base
  fade_on_empty = false
  rounding = -1
  placeholder_text = 
  font_family = SF Pro Display, CaskaydiaCove Nerd Font Propo

  position = 0, -400
  halign = center
  valign = center
}

# TIME
label {
  text = $TIME
  position = 0, 320 
  font_size = 110
  font_family = SF Pro Display Bold
  color = rgba(255, 255, 255, 0.4)
}

#USER 
label {
  text =  $USER
  position = 0, -360
  font_size = 15
  font_family = SF Pro Display Bold, CaskaydiaCove Nerd Font Propo
  color = rgba(255, 255, 255, 0.5)
}

# DATE 
label {
  monitor = 
  text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
  color = rgba(255, 255, 255, 0.4)
  font_size = 15
  font_family = SF Pro Display Bold
  position = 0, 410
  halign = center
  valign = center
}

